### ISSUE TITLE
typo in about and readme.md -- "binding" not "biding"

### ISSUE THREAD

**Issue by Beliavsky** [Cuda-Chen/libmseed-fortran-binding-demo#1]
typo in about and readme.md -- "binding" not "biding"

**Comment by Cuda-Chen** [comment]
Hi @Beliavsky ,

Thanks for your help, the typo is fixed in https://github.com/Cuda-Chen/libmseed-fortran-binding-demo/commit/c82781940531379aa4e146b0dc43427b98f07455
